name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        
      - name: Build with PyInstaller
        run: pyinstaller --noconfirm --onefile --windowed --icon "Assets/icon.ico" --add-data="Assets;Assets/" --name "autoexec" "autoexec.py"
        
      - name: Calculate MD5 hash
        run: |
          cd dist
          md5sum *.exe > checksums.txt
          
      - name: Upload checksums.txt
        uses: actions/upload-artifact@v4
        with:
          name: checksums.txt
          path: dist/checksums.txt
          
      - name: Upload autoexec.exe 
        uses: actions/upload-artifact@v4
        with:
          name: autoexec.exe
          path: dist/autoexec.exe
